# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Home
email: cdestephen@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.clementdestephen.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
#github_username:  clement-destephen
soundcloud_username: clementdestephen
linkedin_username: clement-destephen
markdown: kramdown
lang: en
languages: ["fr", "en"]

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: pages
    values:
      layout: page
  - scope:
      path: "*/index.md"
      type: pages
    values:
      layout: home
  - scope:
      type: portfolio
    values:
      layout: page
  - scope:
      type: publications
    values:
      layout: page
  - scope:
      path: "*/feed.xml"
    values:
      layout: feed
  - scope:
      path: fr
    values:
      lang: fr
  - scope:
      path: en
    values:
      lang: en
  - scope:
      path: "_publications/fr"
      type: publications
    values:
      lang: fr
  - scope:
      path: "_publications/en"
      type: publications
    values:
      lang: en
  - scope:
      path: "_portfolio/fr"
      type: portfolio
    values:
      lang: fr
  - scope:
      path: "_portfolio/en"
      type: portfolio
    values:
      lang: en
  - scope:
      path: "_posts/fr"
      type: posts
    values:
      lang: fr
  - scope:
      path: "_posts/en"
      type: posts
    values:
      lang: en